blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='Slug', unique=True)
    context = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Превью')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    publication_sign = models.BooleanField(default=True, verbose_name='Признак публикации')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


# Create your views here.
class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'context', 'image', 'publication_sign')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_sign=True)
        return queryset

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object

class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'context', 'image', 'publication_sign')
    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class='col-6'>
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {%csrf_token%}
                        <p>Хотите удалить блог "{{object.title}}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% load my_filters %}

{% block content%}

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        Блог  "{{ object.title }}" ({{ object.slug }})
                    </h4>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.context }}
                    </p>
                    <img class="img"
                         src="{{ object.image|blog_mediapath }}"
                         alt="{{ blog.name }}"
                         width="200"
                         height="250"
                    >
                </div>
                <div class="card-footer">
                    Опубликован: {{ object.creation_date }}
                </div>
                <div class="card-footer">
                    Просмотры {{ object.views }}
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class='col-6'>
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content%}
<div class="col-12 mb-5">
  <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
</div>
{% for object in object_list %}
<div class="container">
  <div class="row text-center">
    <div class="col-3">
      <div class="card mb-4 box shadow">
        <div class="card-body">
          <p class="card-text">
            {{ object|title }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{% url 'blog:view' object.pk %}"
                 class="btn btn-sm btn-outline secondary">View</a>
              {% if user.is_authenticated %}
              <a href="{% url 'blog:edit' object.pk %}"
                 class="btn btn-sm btn-outline secondary">Edit</a>
              <a href="{% url 'blog:delete' object.pk %}"
                 class="btn btn-sm btn-outline secondary">Delete</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}