blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserDetailView, confirm_email, activate_email, password_reset
from utils.utils import generate_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/view', UserDetailView.as_view(), name='profile_view'),
    path("profile/generate_password", generate_password, name="generate_password_profile"),
    path('confirm', confirm_email, name='confirm'),
    path('activate<str:key>', activate_email, name='activate'),

    path('password_reset/', password_reset, name='password_reset'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    email_is_confirmed = models.BooleanField(default=False, verbose_name='подтверждено')
    email_confirm_key = models.CharField(max_length=30, verbose_name='код подтверждения почты', **NULLABLE)

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(**NULLABLE, verbose_name='страна')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from builtins import super

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from utils.utils import confirm_user_email, create_secret_key


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile_view')

    def get_object(self, queryset=None):
        return self.request.user


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


def confirm_email(request):
    """подтверждаем почту"""
    confirm_user_email(request, request.user)
    return redirect(reverse('users:profile'))


def activate_email(request, key):
    """активируем почту"""
    print(request.user.email_confirm_key, key, sep='\n')
    if request.user.email_confirm_key == key:
        request.user.email_is_confirmed = True
        request.user.email_confirm_key = None
        request.user.save()
    else:
        print('Ключ не актуален')
    return redirect('/')


def password_reset(request):
    """генерируем пароль для неавторизованного пользователя"""
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = create_secret_key(12)
            user.set_password(new_password)
            user.save()
            login(request, user)

            send_mail(
                subject='Вы сменили пароль',
                message=f'Новый пароль {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[request.user.email]
            )

            return redirect(reverse("users:login"))# все ок -> логин
        # не ок -> Error message + остаемся тут же
        except User.DoesNotExist:
            return render(request, 'users/password_reset_form.html',
                          {'error_message': 'Такого пользователя не существует'})
    return render(request, 'users/password_reset_form.html')

users/templates/users/confirm_email_message.html
{% autoescape off %}
Для подтверждения почтового адреса перейдите по ссылке:
http://{{ domain }}{% url 'users:activate' key %}
{% endautoescape %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load filters %}
{% block content%}
<div class="row mt-2 justify-content-center">
    <div class="col-6">
        <div class="card text-center">
            <div class="card-body">
                <h4 class="card-title">Вход</h4>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Войти">
                        <a href="{% url 'users:password_reset' %}" class="btn btn-danger w-50 mt-2">Сгенерировать новый пароль</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-3">
      <div class="card mb-4 box-shadow">
        <div class="card-header">

          <h3>Забыли пароль?</h3>
          <p>Введите e-mail, вам будет отправлено письмо</p>


          <form method="post">
            {% csrf_token %}
            <input type="email" name="email" placeholder="Email" required>
            {% if error_message %}
            <p style="color: red;">{{ error_message }}</p>
            {% endif %}
            <button type="submit" class="btn btn-primary">Отправить e-mail</button>
          </form>

        </div>
      </div>
    </div>
  </div>


  {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load filters %}
{% block content%}
<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class='card'>
        <div class="card-header">
          <h4 class="card-title">
            Регистрация
          </h4>
        </div>
        <div class='col-8 mb-4'>
          <div class="card">
            <div class="card-body" >
              {%csrf_token%}
              {{ form.as_p }}
              <button type="submit" class="btn btn-success">
                Зарегистрироваться
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </form>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'catalog/base.html' %}
{% load filters %}
{% block content%}
<div class="row mt-2 justify-content-center">
  <div class="col-6">
    <div class="card">
      <p style="text-align: center;">
        <img src="{% mediapath object.avatar %}" alt="{{ object.first_name }}" style="max-height:225px; max-width:100%; width: auto; height: auto;">
      </p>
      <div class="card-body">
        <p class="card-text">email: {{ object.email }}
          {% if not user.is_superuser %}
          {% if object.email_is_confirmed %}
          <span class="badge text-success">Подтверждён</span><br>
          {% else %}
          <a href="{% url 'users:confirm' %}" class="btn btn-sm btn-danger">Подтвердить</a>
          {% endif %}<br>
          {% endif %}
          {% if object %}
        <h5 class="card-title">{{ object.first_name }} {{ object.last_name }}</h5>
        Телефон: {{ object.phone }}<br>
        Страна: {{ object.country }}</p>
        {% endif %}
        <div class="btn-group">
          <a href="{% url 'users:profile' %}" class="btn btn-warning">Редактировать</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load filters %}
{% block content%}
<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <div class="card-title">
            <h3>Профиль</h3>
          </div>
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Сохранить</button>
          <a href="{% url 'users:generate_password_profile' %}" class="btn btn-danger w-50 mt-2">Сгенерировать новый пароль</a>

        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}